language: python
sudo: false
python:
  - "3.6"
  - "3.7"
env:
  - SESSION="test(drf='3.8', django='2.0')"
  - SESSION="test(drf='3.9', django='2.0')"
  - SESSION="test(drf='3.8', django='2.1')"
  - SESSION="test(drf='3.9', django='2.1')"
  - SESSION="test(drf='3.8', django='2.2')"
  - SESSION="test(drf='3.9', django='2.2')"
  - SESSION="black"
  - SESSION="mypy"
install:
  - pip install pipx
  - pipx install nox
script:
  - nox -s "$SESSION"
after_success:
  - bash <(curl -s https://codecov.io/bash)
